- name: etcd-ca
  baseName: etcd/ca
  caName: ""
  cfg:
    algorithm: 1
    commonName: etcd-ca
    # In years, ignoring leap years， 1 year = 365 day
    duration: 99
- name: etcd-server
  baseName: etcd/server
  caName: "etcd-ca"
  cfg:
    algorithm: 1
    usages:
      - 1
      - 2
    altNames:
      dns:
        - localhost
        - etcd.test.com
      ips:
        - 127.0.0.1
        - 192.168.234.137
    commonName: etcd-server
    organization:
      - "system:master"
